# Generated by Django 5.0.2 on 2024-03-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="badge",
            field=models.CharField(default="0", max_length=5),
        ),
    ]
# Generated by Django 5.0.3 on 2024-03-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='badge',
            field=models.CharField(default='0', max_length=5),
        ),
    ]
