# Generated by Django 5.0.2 on 2024-02-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0002_userschallenges"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="cType",
            field=models.CharField(
                choices=[
                    ("Location-Based", "Location-Based"),
                    ("Non Location-Based", "Non Location-Based"),
                ],
                max_length=100,
            ),
        ),
    ]
