# Generated by Django 4.1 on 2024-02-25 14:55

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_alter_challenge_ctype'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
