# Generated by Django 5.0.3 on 2024-03-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_player_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='numChallenges',
            field=models.IntegerField(default=0),
        ),
    ]
