# Generated by Django 5.0.3 on 2024-03-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_player_numchallenges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='numChallenges',
            field=models.IntegerField(),
        ),
    ]
