# Generated by Django 5.0.3 on 2024-03-21 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_player_numchallenges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamekeeper',
            name='user',
        ),
        migrations.DeleteModel(
            name='Developer',
        ),
        migrations.DeleteModel(
            name='GameKeeper',
        ),
    ]
